builds:
  -
    goos:
      - darwin
      - linux
    goarch:
      - 386
      - amd64
    ignore:
      - goos: darwin
        goarch: 386
archive:
  format: zip
  replacements:
    386: 32-bit
    amd64: 64-bit
    darwin: macOS
    linux: Linux
release:
  draft: false
brew:
  github:
    owner: skatsuta
    name: homebrew-athenai
  folder: Formula
  homepage: https://github.com/skatsuta/athenai
  description: Athenai is a simple and easy-to-use command line tool that runs SQL statements on Amazon Athena.
  install: |
    bin.install "athenai"
