builds:
  -
    goos:
      - darwin
      - linux
      # - windows
    goarch:
      - 386
      - amd64
    ignore:
      - goos: darwin
        goarch: 386
archive:
  name_template: '{{ .Binary }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
  replacements:
    darwin: macOS
    linux: Linux
    windows: Windows
    386: 32-bit
    amd64: 64-bit
  format_overrides:
    - goos: windows
      format: zip
release:
  draft: false
brew:
  github:
    owner: skatsuta
    name: homebrew-athenai
  folder: Formula
  homepage: https://github.com/skatsuta/athenai
  description: |
    Athenai is a simple and easy-to-use command line tool that runs SQL query statements on Amazon Athena.
  install: |
    bin.install "athenai"
